{"name": "Проверяем, что курьер не может залогиниться с невалидным паролем, запрос возвращает ошибку с кодом 404", "status": "passed", "start": 1727696273526, "stop": 1727696273998, "uuid": "d07f31cb-aab8-4b96-a022-f6301f7ecbcc", "historyId": "9c67360aac606cacb5b7d0039cbc7124", "testCaseId": "9c67360aac606cacb5b7d0039cbc7124", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_invalid_password_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "hanastasia-mbby"}, {"name": "thread", "value": "14322-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}