{"name": "Проверяем, что курьер не может залогиниться с невалидным паролем, запрос возвращает ошибку с кодом 404", "status": "passed", "start": 1727466559197, "stop": 1727466559506, "uuid": "b2eaff73-6074-44d1-9a4f-18be99659a42", "historyId": "9c67360aac606cacb5b7d0039cbc7124", "testCaseId": "9c67360aac606cacb5b7d0039cbc7124", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_invalid_password_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "hanastasia-mbby"}, {"name": "thread", "value": "97967-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}